discovery:
  portOptions: No, Yes
  supportedTypes: IP, Range, Subnet
server:
  port: ${PORT:8090}
spring:
  datasource:
    auto-commit: false
    driver-class-name: org.postgresql.Driver
    password: ${JDBC_PASSWORD}
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
  flyway:
    out-of-order: true
    table: "network_schema_history"
    schemas: ${DB_SCHEMA:network}
  jpa:
    properties:
      hibernate.default_schema: ${DB_SCHEMA:network}
